# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9dc7d67568589570253ec2d6a00a47afed414c8b85dbfd82fe453a21937907f684daaa461132a814fabb6e724ffcbce9b76b5638d658c9fc785467c7a378ff34

test:
  secret_key_base: 1408bc119dafe42d8b29c47f2992ecd6eb5074466d1887c1568cef7fdec28f30d6473d45249e2f5f2a5eb1e341125ea687c0c3551065cbd1c00150794c72eba6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
